name: CI

on:
  pull_request:

jobs:
  package-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync
        working-directory: my-service

      - name: Build package
        run: uv build
        working-directory: my-service

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI passed"
